// File generated by FlutterFire CLI.
// Do not modify manually.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:firebase_core/firebase_core.dart';
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI command: '
          '`flutterfire configure --platforms=macos`',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI command: '
          '`flutterfire configure --platforms=windows`',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI command: '
          '`flutterfire configure --platforms=linux`',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configuration for your web app, updated with the 'furrytails-bb67e' project details
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkilaO0lkU42PWBewZ-Bi46rjpsLnVrg',
    appId: '1:896556655663:web:326868542f160af74a12da',
    messagingSenderId: '896556655663',
    projectId: 'furrytails-bb67e',
    authDomain: 'furrytails-bb67e.firebaseapp.com',
    storageBucket: 'furrytails-bb67e.firebasestorage.app',
    measurementId: 'G-8K12SR15KR',
  );

  // Placeholder for Android configuration - updated project details
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'YOUR_ANDROID_API_KEY', // <--- This will be your actual Android API Key
    appId:
        '1:896556655663:android:xxxxxxxxxxxxxxxxxxxx', // <--- This will be your actual Android App ID
    messagingSenderId: '896556655663',
    projectId: 'furrytails-bb67e',
    storageBucket: 'furrytails-bb67e.appspot.com',
  );

  // Placeholder for iOS configuration - updated project details
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // <--- This will be your actual iOS API Key
    appId:
        '1:896556655663:ios:xxxxxxxxxxxxxxxxxxxx', // <--- This will be your actual iOS App ID
    messagingSenderId: '896556655663',
    projectId: 'furrytails-bb67e',
    storageBucket: 'furrytails-bb67e.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.customer1', // Or your actual bundle ID
  );
}
