// File generated by FlutterFire CLI.
// Do not modify manually.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:firebase_core/firebase_core.dart';
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI command: '
          '`flutterfire configure --platforms=macos`',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI command: '
          '`flutterfire configure --platforms=windows`',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI command: '
          '`flutterfire configure --platforms=linux`',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configuration for your web app based on your provided details
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiP2p3gbGtcgILDfppKpuuA4Q5awURzI4',
    appId: '1:379925509921:web:ba47588771992d293cb060',
    messagingSenderId: '379925509921',
    projectId: 'admin-a95e4',
    authDomain: 'admin-a95e4.firebaseapp.com',
    storageBucket: 'admin-a95e4.firebasestorage.app',
    measurementId: 'G-ERG3RPY2GX',
  );

  // Placeholder for Android configuration - will be filled by flutterfire configure
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'YOUR_ANDROID_API_KEY', // <--- This will be your actual Android API Key
    appId:
        '1:379925509921:android:xxxxxxxxxxxxxxxxxxxx', // <--- This will be your actual Android App ID
    messagingSenderId: '379925509921',
    projectId: 'admin-a95e4',
    storageBucket: 'admin-a95e4.appspot.com',
  );

  // Placeholder for iOS configuration - will be filled by flutterfire configure
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // <--- This will be your actual iOS API Key
    appId:
        '1:379925509921:ios:xxxxxxxxxxxxxxxxxxxx', // <--- This will be your actual iOS App ID
    messagingSenderId: '379925509921',
    projectId: 'admin-a95e4',
    storageBucket: 'admin-a95e4.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.customer1', // Or your actual bundle ID
  );
}
